[project]
name = "cubewalkers"
authors = [{ name = "Jordan Rozum", email = "jrozum@binghamton.edu" }]
version = "1.3.5"
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]
cana = ["cana"]
